<script setup lang="ts">
import { ref, onMounted } from 'vue';
import {
  SparklesIcon,
  ArrowPathIcon,
  ArrowDownTrayIcon,
  CalendarIcon,
  ClockIcon,
  ChartBarIcon,
  CheckCircleIcon,
  XCircleIcon,
  DocumentArrowDownIcon,
  MapPinIcon,
  RocketLaunchIcon,
  BeakerIcon
} from '@heroicons/vue/24/outline';

const api = useApi();
const goal = ref("");
const roadmap = ref<any>(null);
const loading = ref(false);
const error = ref("");
const past = ref<any[]>([]);
const isDownloading = ref(false);

async function loadPast() {
  try {
    past.value = await api.get("/roadmap");
  } catch (e) {
    // ignore
  }
}
onMounted(loadPast);

async function generate() {
  if (!goal.value.trim()) return;
  loading.value = true;
  error.value = "";
  try {
    roadmap.value = await api.post("/roadmap", { goal: goal.value });
    await loadPast();
  } catch (e: any) {
    error.value = e?.data?.detail || "Couldn't generate a roadmap. Try again.";
  } finally {
    loading.value = false;
  }
}

async function selectRoadmap(id: string) {
  loading.value = true;
  error.value = "";
  try {
    roadmap.value = await api.get(`/roadmap/${id}`);
  } catch (e: any) {
    error.value = e?.data?.detail || "Couldn't load roadmap details.";
  } finally {
    loading.value = false;
  }
}

async function downloadPDF() {
  if (!roadmap.value) return;

  isDownloading.value = true;
  try {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ unit: "pt", format: "a4" });

    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 48;
    const contentWidth = pageWidth - margin * 2;
    const pageHeight = doc.internal.pageSize.getHeight();
    let y = margin;

    const chart = [79, 209, 197];
    const ink = [26, 26, 46];
    const muted = [102, 102, 102];

    function ensureSpace(nextBlockHeight: number) {
      if (y + nextBlockHeight > pageHeight - margin) {
        doc.addPage();
        y = margin;
      }
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(ink[0], ink[1], ink[2]);
    const titleLines = doc.splitTextToSize(roadmap.value.goal || "My Roadmap", contentWidth);
    doc.text(titleLines, margin, y);
    y += titleLines.length * 26 + 4;

    doc.setDrawColor(chart[0], chart[1], chart[2]);
    doc.setLineWidth(1.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 18;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(muted[0], muted[1], muted[2]);
    const monthsCount = roadmap.value.months?.length || 0;
    doc.text(`Generated: ${new Date().toLocaleDateString()}${monthsCount ? ` · ${monthsCount} months` : ""}`, margin, y);
    y += 22;

    if (roadmap.value.summary) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(11);
      doc.setTextColor(68, 68, 68);
      const summaryLines = doc.splitTextToSize(roadmap.value.summary, contentWidth);
      ensureSpace(summaryLines.length * 14 + 20);
      doc.text(summaryLines, margin, y);
      y += summaryLines.length * 14 + 24;
    }

    for (const m of roadmap.value.months || []) {
      ensureSpace(80);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(chart[0], chart[1], chart[2]);
      doc.text(`MONTH ${m.month}`, margin, y);
      y += 16;

      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.setTextColor(ink[0], ink[1], ink[2]);
      const monthTitleLines = doc.splitTextToSize(m.title || "", contentWidth);
      ensureSpace(monthTitleLines.length * 16 + 10);
      doc.text(monthTitleLines, margin, y);
      y += monthTitleLines.length * 16 + 6;

      if (m.focus_areas?.length) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(45, 125, 122);
        const focusLine = m.focus_areas.join("   ·   ");
        const focusLines = doc.splitTextToSize(focusLine, contentWidth);
        ensureSpace(focusLines.length * 12 + 6);
        doc.text(focusLines, margin, y);
        y += focusLines.length * 12 + 8;
      }

      if (m.milestones?.length) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10.5);
        doc.setTextColor(60, 60, 60);
        for (const ms of m.milestones) {
          const bulletLines = doc.splitTextToSize(`•  ${ms}`, contentWidth - 10);
          ensureSpace(bulletLines.length * 13 + 4);
          doc.text(bulletLines, margin + 10, y);
          y += bulletLines.length * 13 + 4;
        }
      }

      y += 18;
    }

    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(150, 150, 150);
      doc.text(
        "Generated by CityOS AI — Your AI-powered opportunity navigator",
        pageWidth / 2,
        pageHeight - 24,
        { align: "center" }
      );
    }

    const filename = `roadmap-${(roadmap.value.goal || "plan").toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "")}.pdf`;
    doc.save(filename);
  } catch (e: any) {
    error.value = "Couldn't download PDF. Please try again.";
  } finally {
    isDownloading.value = false;
  }
}
</script>

<template>
  <div class="min-h-screen bg-navy-950 relative">
    <!-- Enhanced Neural Network Background -->
    <div class="absolute inset-0 pointer-events-none overflow-hidden opacity-[0.04]">
      <svg class="absolute inset-0 h-full w-full" xmlns="http://www.w3.org/2000/svg">
        <!-- Primary Nodes -->
        <g v-for="i in 35" :key="i">
          <circle 
            :cx="Math.random() * 100 + '%'" 
            :cy="Math.random() * 100 + '%'" 
            r="2.5" 
            fill="#4FD1C5"
            class="animate-pulse"
            :style="{ animationDelay: (i * 0.08) + 's' }"
          />
        </g>
        <!-- Secondary Nodes -->
        <g v-for="i in 25" :key="'secondary-' + i">
          <circle 
            :cx="Math.random() * 100 + '%'" 
            :cy="Math.random() * 100 + '%'" 
            r="1.5" 
            fill="#F2B84B"
            class="animate-pulse"
            :style="{ animationDelay: (i * 0.12 + 0.5) + 's' }"
          />
        </g>
        <!-- Neural Connections -->
        <g v-for="i in 18" :key="'conn-' + i">
          <line 
            :x1="Math.random() * 100 + '%'" 
            :y1="Math.random() * 100 + '%'" 
            :x2="Math.random() * 100 + '%'" 
            :y2="Math.random() * 100 + '%'" 
            stroke="#4FD1C5" 
            stroke-width="0.5"
            opacity="0.3"
          />
        </g>
        <!-- Data Flow Path -->
        <path 
          d="M 5% 20% Q 25% 10% 45% 30% T 70% 25% T 90% 40%" 
          stroke="#4FD1C5" 
          stroke-width="1"
          fill="none"
          opacity="0.15"
          stroke-dasharray="4 4"
        />
        <path 
          d="M 8% 60% Q 30% 75% 50% 60% T 75% 70% T 92% 55%" 
          stroke="#4FD1C5" 
          stroke-width="1"
          fill="none"
          opacity="0.12"
          stroke-dasharray="3 6"
        />
      </svg>
    </div>

    <!-- Decorative Node Clusters -->
    <div class="absolute inset-0 pointer-events-none overflow-hidden opacity-[0.02]">
      <div class="absolute top-[10%] left-[8%]">
        <div class="flex items-center gap-6">
          <div class="h-4 w-4 rounded-full bg-chart-400"></div>
          <div class="h-px w-20 bg-chart-400/20"></div>
          <div class="h-3 w-3 rounded-full bg-chart-400"></div>
          <div class="h-px w-12 bg-chart-400/20"></div>
          <div class="h-2 w-2 rounded-full bg-chart-400"></div>
        </div>
      </div>
      <div class="absolute bottom-[15%] right-[8%]">
        <div class="flex items-center gap-6">
          <div class="h-2 w-2 rounded-full bg-chart-400"></div>
          <div class="h-px w-16 bg-chart-400/20"></div>
          <div class="h-3 w-3 rounded-full bg-chart-400"></div>
          <div class="h-px w-20 bg-chart-400/20"></div>
          <div class="h-4 w-4 rounded-full bg-chart-400"></div>
        </div>
      </div>
    </div>

    <!-- Radial Gradient Overlay -->
    <div class="absolute inset-0 pointer-events-none bg-[radial-gradient(ellipse_at_center,_transparent_0%,_#0A0E1A_100%)] opacity-60"></div>

    <AppNav />
    <main class="relative z-10 mx-auto max-w-4xl px-4 sm:px-6 py-8 sm:py-12">
      
      <!-- Header -->
      <div class="mb-8 pb-6 border-b border-navy-800/50">
        <div class="flex items-center gap-3 mb-2">
          <span class="inline-flex items-center gap-2 rounded-full bg-chart-400/10 px-3 py-1 text-xs font-mono text-chart-400 border border-chart-400/10">
            <SparklesIcon class="h-3 w-3" />
            Phase 6
          </span>
          <span class="text-xs font-mono text-navy-500">·</span>
          <span class="text-xs font-mono text-navy-500">Roadmap Generator</span>
        </div>
        <h1 class="text-2xl sm:text-3xl font-display font-medium text-parchment tracking-tight flex items-center gap-3">
          <MapPinIcon class="h-6 w-6 text-chart-400" />
          Your Roadmap
        </h1>
        <p class="mt-1.5 text-sm text-navy-400">Tell us where you want to go. We'll chart the months to get there.</p>
      </div>

      <!-- Input Section -->
      <div class="rounded-xl bg-navy-900/40 border border-navy-800/50 p-5 sm:p-6 backdrop-blur-sm transition-all hover:border-navy-700/70">
        <form @submit.prevent="generate" class="space-y-4">
          <div>
            <label class="block text-xs font-mono text-navy-400 uppercase tracking-wider mb-1.5 flex items-center gap-2">
              <RocketLaunchIcon class="h-3.5 w-3.5" />
              Your goal
            </label>
            <div class="relative">
              <input 
                v-model="goal" 
                class="w-full rounded-lg bg-navy-950/50 border border-navy-800/50 px-4 py-3 text-parchment placeholder-navy-500 focus:border-chart-400/50 focus:outline-none focus:ring-1 focus:ring-chart-400/20 transition-all" 
                placeholder="e.g. I want to become an AI Engineer" 
              />
              <div class="absolute right-3 top-1/2 -translate-y-1/2 flex items-center gap-1.5">
                <div v-if="goal.length > 0" class="h-1.5 w-1.5 rounded-full bg-chart-400 animate-pulse"></div>
              </div>
            </div>
          </div>
          
          <div class="flex items-center gap-4">
            <button 
              type="submit" 
              class="inline-flex items-center gap-2 rounded-lg bg-chart-400/10 px-5 py-2.5 text-sm font-medium text-chart-400 border border-chart-400/20 hover:bg-chart-400/20 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
              :disabled="loading || !goal.trim()"
            >
              <ArrowPathIcon v-if="loading" class="h-4 w-4 animate-spin" />
              <SparklesIcon v-else class="h-4 w-4" />
              {{ loading ? "Generating..." : "Generate Roadmap" }}
            </button>
            <p v-if="error" class="text-sm text-coral-400 flex-1 flex items-center gap-2">
              <XCircleIcon class="h-4 w-4 flex-shrink-0" />
              <span>{{ error }}</span>
            </p>
          </div>
        </form>
      </div>

      <!-- Roadmap Display -->
      <section v-if="roadmap" class="mt-10">
        <div class="items-start justify-between gap-4 mb-6 pb-4 border-b border-navy-800/50">
          <div>
            <h2 class="text-lg font-medium text-parchment flex items-center gap-2">
              <CheckCircleIcon class="h-5 w-5 text-chart-400" />
              {{ roadmap.goal }}
            </h2>
            <p class="mt-1 text-sm text-navy-400">{{ roadmap.summary }}</p>
          </div>
          <div class="flex items-center gap-3 shrink-0">
            <div class="rounded-full bg-navy-800/30 px-3 py-1 text-xs font-mono text-chart-400 border border-navy-700/50 flex items-center gap-1.5">
              <CalendarIcon class="h-3 w-3" />
              {{ roadmap.months?.length || 0 }} months
            </div>
            <button 
              @click="downloadPDF"
              :disabled="isDownloading"
              class="inline-flex items-center gap-2 rounded-lg bg-navy-800/30 px-3.5 py-2 text-sm font-medium text-parchment border border-navy-700/50 hover:bg-navy-800/50 hover:border-chart-400/30 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <DocumentArrowDownIcon v-if="!isDownloading" class="h-4 w-4" />
              <ArrowPathIcon v-else class="h-4 w-4 animate-spin" />
              {{ isDownloading ? "Preparing..." : "Download PDF" }}
            </button>
          </div>
        </div>

        <!-- Timeline with Neural Flow -->
        <div class="relative">
          <!-- Vertical Connector with Neural Flow -->
          <div class="absolute left-4 top-0 bottom-0 w-px bg-gradient-to-b from-chart-400/30 via-chart-400/10 to-transparent">
            <div class="absolute top-1/2 -translate-y-1/2 -left-[2px] h-3 w-3 rounded-full bg-chart-400/20 animate-pulse"></div>
          </div>

          <ol class="space-y-6">
            <li v-for="(m, index) in roadmap.months" :key="m.month" class="relative pl-12 group">
              <!-- Month Node -->
              <div class="absolute left-0 top-1.5 flex items-center justify-center">
                <div class="h-8 w-8 rounded-full bg-navy-800/50 border-2 border-chart-400/30 flex items-center justify-center group-hover:border-chart-400/60 transition-all">
                  <span class="text-xs font-mono font-medium text-chart-400">M{{ m.month }}</span>
                </div>
                <div class="absolute inset-0 rounded-full bg-chart-400/5 animate-pulse"></div>
                <!-- Neural Connection Dot -->
                <div class="absolute -right-8 top-1/2 -translate-y-1/2 h-1.5 w-1.5 rounded-full bg-chart-400/20 group-hover:bg-chart-400/40 transition-colors"></div>
              </div>

              <div class="rounded-xl bg-navy-900/40 border border-navy-800/50 p-5 sm:p-6 backdrop-blur-sm transition-all hover:border-navy-700/70 group-hover:bg-navy-900/50">
                <div class="flex items-start justify-between gap-4">
                  <h3 class="text-base font-medium text-parchment">{{ m.title }}</h3>
                  <ChartBarIcon class="h-4 w-4 text-navy-500 group-hover:text-chart-400 transition-colors flex-shrink-0" />
                </div>
                
                <div class="mt-3 flex flex-wrap gap-2">
                  <span v-for="f in m.focus_areas" :key="f" class="rounded-full bg-chart-400/5 border border-chart-400/15 px-3 py-1 text-xs text-chart-400 flex items-center gap-1">
                    <BeakerIcon class="h-2.5 w-2.5" />
                    {{ f }}
                  </span>
                </div>
                
                <ul class="mt-3 space-y-1.5">
                  <li v-for="ms in m.milestones" :key="ms" class="flex items-start gap-2 text-sm text-navy-400">
                    <span class="mt-1.5 h-1 w-1 rounded-full bg-chart-400/40 flex-shrink-0"></span>
                    {{ ms }}
                  </li>
                </ul>

                <div class="mt-4 flex items-center gap-2">
                  <div class="flex-1 h-1 rounded-full bg-navy-800/50 overflow-hidden">
                    <div class="h-full rounded-full bg-gradient-to-r from-chart-400/30 to-chart-400 transition-all duration-1000" :style="{ width: ((index + 1) / roadmap.months.length * 100) + '%' }"></div>
                  </div>
                  <span class="text-[10px] font-mono text-navy-500 flex items-center gap-1">
                    <ClockIcon class="h-2.5 w-2.5" />
                    {{ Math.round((index + 1) / roadmap.months.length * 100) }}%
                  </span>
                </div>
              </div>
            </li>
          </ol>
        </div>
      </section>

      <!-- Past Roadmaps -->
      <section v-if="past.length" class="mt-12 pt-8 border-t border-navy-800/50">
        <h2 class="text-sm font-medium text-parchment mb-4 flex items-center gap-2">
          <ClockIcon class="h-4 w-4 text-navy-400" />
          <span>Past Roadmaps</span>
          <span class="rounded-full bg-navy-800/50 px-2 py-0.5 text-xs font-mono text-navy-400">{{ past.length }}</span>
        </h2>
        <div class="grid gap-2 sm:grid-cols-2">
          <button 
            v-for="r in past" 
            :key="r.id"
            @click="selectRoadmap(r.id)" 
            class="group text-left rounded-lg bg-navy-900/30 border border-navy-800/50 px-4 py-3 transition-all hover:border-navy-700/70 hover:bg-navy-900/50"
          >
            <p class="text-sm text-parchment group-hover:text-chart-400 transition-colors truncate flex items-center gap-2">
              <MapPinIcon class="h-3.5 w-3.5 text-navy-500 group-hover:text-chart-400 transition-colors" />
              {{ r.goal }}
            </p>
            <p class="text-xs text-navy-500 mt-0.5 flex items-center gap-1.5">
              <CalendarIcon class="h-2.5 w-2.5" />
              {{ r.created_at }}
            </p>
          </button>
        </div>
      </section>
    </main>
  </div>
</template>